# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CharCounter_create <- function() {
    .Call(`_seqtrie_CharCounter_create`)
}

CharCounter_add <- function(xp, sequences) {
    invisible(.Call(`_seqtrie_CharCounter_add`, xp, sequences))
}

CharCounter_subtract <- function(xp, sequences) {
    invisible(.Call(`_seqtrie_CharCounter_subtract`, xp, sequences))
}

CharCounter_keys <- function(xp) {
    .Call(`_seqtrie_CharCounter_keys`, xp)
}

get_charset <- function(sequences) {
    .Call(`_seqtrie_get_charset`, sequences)
}

RadixForest_size <- function(xp) {
    .Call(`_seqtrie_RadixForest_size`, xp)
}

RadixForest_insert <- function(xp, sequences) {
    .Call(`_seqtrie_RadixForest_insert`, xp, sequences)
}

RadixForest_erase <- function(xp, sequences) {
    .Call(`_seqtrie_RadixForest_erase`, xp, sequences)
}

RadixForest_find <- function(xp, sequences) {
    .Call(`_seqtrie_RadixForest_find`, xp, sequences)
}

RadixForest_prefix_search <- function(xp, sequences) {
    .Call(`_seqtrie_RadixForest_prefix_search`, xp, sequences)
}

RadixForest_print <- function(xp) {
    .Call(`_seqtrie_RadixForest_print`, xp)
}

RadixForest_graph <- function(xp, max_depth) {
    .Call(`_seqtrie_RadixForest_graph`, xp, max_depth)
}

RadixForest_to_vector <- function(xp) {
    .Call(`_seqtrie_RadixForest_to_vector`, xp)
}

RadixForest_validate <- function(xp) {
    .Call(`_seqtrie_RadixForest_validate`, xp)
}

RadixForest_create <- function() {
    .Call(`_seqtrie_RadixForest_create`)
}

RadixForest_search <- function(xp, query, max_distance, mode = "global", nthreads = 1L, show_progress = FALSE) {
    .Call(`_seqtrie_RadixForest_search`, xp, query, max_distance, mode, nthreads, show_progress)
}

RadixTree_size <- function(xp) {
    .Call(`_seqtrie_RadixTree_size`, xp)
}

RadixTree_insert <- function(xp, sequences) {
    .Call(`_seqtrie_RadixTree_insert`, xp, sequences)
}

RadixTree_erase <- function(xp, sequences) {
    .Call(`_seqtrie_RadixTree_erase`, xp, sequences)
}

RadixTree_find <- function(xp, sequences) {
    .Call(`_seqtrie_RadixTree_find`, xp, sequences)
}

RadixTree_prefix_search <- function(xp, sequences) {
    .Call(`_seqtrie_RadixTree_prefix_search`, xp, sequences)
}

RadixTree_print <- function(xp) {
    .Call(`_seqtrie_RadixTree_print`, xp)
}

RadixTree_graph <- function(xp, max_depth) {
    .Call(`_seqtrie_RadixTree_graph`, xp, max_depth)
}

RadixTree_to_vector <- function(xp) {
    .Call(`_seqtrie_RadixTree_to_vector`, xp)
}

RadixTree_validate <- function(xp) {
    .Call(`_seqtrie_RadixTree_validate`, xp)
}

RadixTree_create <- function() {
    .Call(`_seqtrie_RadixTree_create`)
}

RadixTree_search <- function(xp, query, max_distance, mode = "global", cost_matrix = NULL, gap_cost = NA_integer_, gap_open_cost = NA_integer_, nthreads = 1L, show_progress = FALSE) {
    .Call(`_seqtrie_RadixTree_search`, xp, query, max_distance, mode, cost_matrix, gap_cost, gap_open_cost, nthreads, show_progress)
}

RadixTree_single_gap_search <- function(xp, query, max_distance, gap_cost = 1L, nthreads = 1L, show_progress = FALSE) {
    .Call(`_seqtrie_RadixTree_single_gap_search`, xp, query, max_distance, gap_cost, nthreads, show_progress)
}

c_dist_matrix <- function(query, target, mode = "global", cost_matrix = NULL, gap_cost = NA_integer_, gap_open_cost = NA_integer_, nthreads = 1L, show_progress = FALSE) {
    .Call(`_seqtrie_c_dist_matrix`, query, target, mode, cost_matrix, gap_cost, gap_open_cost, nthreads, show_progress)
}

c_dist_pairwise <- function(query, target, mode = "levenshtein", cost_matrix = NULL, gap_cost = NA_integer_, gap_open_cost = NA_integer_, nthreads = 1L, show_progress = FALSE) {
    .Call(`_seqtrie_c_dist_pairwise`, query, target, mode, cost_matrix, gap_cost, gap_open_cost, nthreads, show_progress)
}

