# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DNATree_create <- function() {
    .Call(`_treedist_DNATree_create`)
}

RadixTree_create <- function() {
    .Call(`_treedist_RadixTree_create`)
}

PrefixTree_create <- function() {
    .Call(`_treedist_PrefixTree_create`)
}

DNATree_size <- function(xp) {
    .Call(`_treedist_DNATree_size`, xp)
}

RadixTree_size <- function(xp) {
    .Call(`_treedist_RadixTree_size`, xp)
}

PrefixTree_size <- function(xp) {
    .Call(`_treedist_PrefixTree_size`, xp)
}

DNATree_print <- function(xp) {
    .Call(`_treedist_DNATree_print`, xp)
}

RadixTree_print <- function(xp) {
    .Call(`_treedist_RadixTree_print`, xp)
}

PrefixTree_print <- function(xp) {
    .Call(`_treedist_PrefixTree_print`, xp)
}

DNATree_insert <- function(xp, sequences) {
    .Call(`_treedist_DNATree_insert`, xp, sequences)
}

RadixTree_insert <- function(xp, sequences) {
    .Call(`_treedist_RadixTree_insert`, xp, sequences)
}

PrefixTree_insert <- function(xp, sequences) {
    .Call(`_treedist_PrefixTree_insert`, xp, sequences)
}

DNATree_erase <- function(xp, sequences) {
    .Call(`_treedist_DNATree_erase`, xp, sequences)
}

RadixTree_erase <- function(xp, sequences) {
    .Call(`_treedist_RadixTree_erase`, xp, sequences)
}

PrefixTree_erase <- function(xp, sequences) {
    .Call(`_treedist_PrefixTree_erase`, xp, sequences)
}

DNATree_find <- function(xp, sequences) {
    .Call(`_treedist_DNATree_find`, xp, sequences)
}

RadixTree_find <- function(xp, sequences) {
    .Call(`_treedist_RadixTree_find`, xp, sequences)
}

PrefixTree_find <- function(xp, sequences) {
    .Call(`_treedist_PrefixTree_find`, xp, sequences)
}

DNATree_to_dataframe <- function(xp) {
    .Call(`_treedist_DNATree_to_dataframe`, xp)
}

RadixTree_to_dataframe <- function(xp) {
    .Call(`_treedist_RadixTree_to_dataframe`, xp)
}

PrefixTree_to_dataframe <- function(xp) {
    .Call(`_treedist_PrefixTree_to_dataframe`, xp)
}

DNATree_levenshtein <- function(xp, sequences, max_distance, nthreads, display_progress) {
    .Call(`_treedist_DNATree_levenshtein`, xp, sequences, max_distance, nthreads, display_progress)
}

RadixTree_levenshtein <- function(xp, sequences, max_distance, nthreads, display_progress) {
    .Call(`_treedist_RadixTree_levenshtein`, xp, sequences, max_distance, nthreads, display_progress)
}

PrefixTree_levenshtein <- function(xp, sequences, max_distance, nthreads, display_progress) {
    .Call(`_treedist_PrefixTree_levenshtein`, xp, sequences, max_distance, nthreads, display_progress)
}

DNATree_hamming <- function(xp, sequences, max_distance, nthreads, display_progress) {
    .Call(`_treedist_DNATree_hamming`, xp, sequences, max_distance, nthreads, display_progress)
}

RadixTree_hamming <- function(xp, sequences, max_distance, nthreads, display_progress) {
    .Call(`_treedist_RadixTree_hamming`, xp, sequences, max_distance, nthreads, display_progress)
}

PrefixTree_hamming <- function(xp, sequences, max_distance, nthreads, display_progress) {
    .Call(`_treedist_PrefixTree_hamming`, xp, sequences, max_distance, nthreads, display_progress)
}

